WebApplication2/Controllers/CardsController.cs
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Utils;

namespace WebApplication2.Controllers
{
    public class CardsController : Controller
    {
		private string customerId = "";

		public CardsController()
		{
			this.customerId = Common.GetCustomerId();
		}

		public ActionResult Index()
		{
			var apiContext = Common.GetApiContext();

			var cards = CreditCard.List(apiContext, externalCustomerId: customerId);

			return View(cards);
		}

		public ActionResult Details(string id)
		{
			var apiContext = Common.GetApiContext();

			var creditCard = CreditCard.Get(apiContext, id);

			return View(creditCard);
		}

		public ActionResult Edit(string id)
		{
			var apiContext = Common.GetApiContext();

			var creditCard = CreditCard.Get(apiContext, id);

			AddPaymentDropdowns();
			return View(creditCard);
		}

		[HttpPost]
		public ActionResult Edit(string id, CreditCard creditCard)
		{
			if (ModelState.IsValid)
			{
				var apiContext = Common.GetApiContext();

				creditCard.type = Common.GetCardType(creditCard.number);
				var existing = CreditCard.Get(apiContext, id);
				if (existing != null)
				{
					var patchRequest = new PatchRequest();

					// determine what's changed between the existing card
					// and the posted values
					if (creditCard.expire_month != existing.expire_month)
					{
						patchRequest.Add(new Patch { op = "replace", path = "/expire_month", value = creditCard.expire_month });
					}

					if (creditCard.expire_year != existing.expire_year)
					{
						patchRequest.Add(new Patch { op = "replace", path = "/expire_year", value = creditCard.expire_year });
					}

					if (!string.IsNullOrEmpty(creditCard.first_name) && creditCard.first_name != existing.first_name)
					{
						patchRequest.Add(new Patch { op = "replace", path = "/first_name", value = creditCard.first_name });
					}

					if (!string.IsNullOrEmpty(creditCard.last_name) && creditCard.last_name != existing.last_name)
					{
						patchRequest.Add(new Patch { op = "replace", path = "/last_name", value = creditCard.last_name });
					}

					if (patchRequest.Count > 0)
					{
						existing.Update(apiContext, patchRequest);

						TempData["success"] = "Stored Card updated.";

						return RedirectToAction("Details", new { id });
					}
					else
					{
						TempData["info"] = "Nothing to update";
					}
				}
			}
			else
			{
				TempData["info"] = "ModelState is invalid";
			}

			AddPaymentDropdowns();
			return View(creditCard);
		}

		public ActionResult Create()
		{
			AddPaymentDropdowns();
			return View();
		}

		[HttpPost]
		public ActionResult Create(CreditCard creditCard)
		{
			if (ModelState.IsValid)
			{
				var apiContext = Common.GetApiContext();

				creditCard.external_customer_id = customerId;
				creditCard.type = Common.GetCardType(creditCard.number);
				creditCard.Create(apiContext);

				TempData["success"] = "Credit card stored successfully";

				return RedirectToAction("Index");
			}

			AddPaymentDropdowns();
			return View(creditCard);
		}

		[HttpPost]
		public ActionResult Delete(string id)
		{
			var apiContext = Common.GetApiContext();

			var creditCard = CreditCard.Get(apiContext, id);

			creditCard.Delete(apiContext);

			TempData["success"] = "Credit card deleted successfully";

			return RedirectToAction("Index");
		}

		private void AddPaymentDropdowns()
		{
			var currentYear = DateTime.Today.Year;
			var years = new List<SelectListItem>();
			for (int i = 0; i < 10; i++)
			{
				years.Add(new SelectListItem { Text = (i + currentYear).ToString(), Value = (i + currentYear).ToString() });
			}

			ViewBag.PossibleYears = years;
			var months = new List<SelectListItem>();
			for (int i = 1; i <= 12; i++)
			{
				months.Add(new SelectListItem { Value = i.ToString(), Text = string.Format("{0} - {1}", i, CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(i)) });
			}

			ViewBag.PossibleMonths = months;
		}
	}
}

WebApplication2/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PayPal.Api;
using WebApplication2.Utils;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class PlansController : Controller
    {
        public ActionResult Index()
        {
			var apiContext = Common.GetApiContext();

			var plans = Plan.List(apiContext, status: "ACTIVE", pageSize: "20");

			return View(plans);
        }

		public ActionResult Create()
		{
			AddDropdowns();
			return View();
		}

		[HttpPost]
		public ActionResult Create(BillingPlan billingPlan)
		{
			if (ModelState.IsValid)
			{
				var apiContext = Common.GetApiContext();

				var plan = new Plan();
				plan.description = billingPlan.Description;
				plan.name = billingPlan.Name;
				plan.type = billingPlan.PlanType;

				plan.merchant_preferences = new MerchantPreferences
				{
					initial_fail_amount_action = "CANCEL",
					max_fail_attempts = "3",
					cancel_url = "http://localhost:50728/plans",
					return_url = "http://localhost:50728/plans"
				};

				plan.payment_definitions = new List<PaymentDefinition>();

				var paymentDefinition = new PaymentDefinition();
				paymentDefinition.name = "Standard Plan";
				paymentDefinition.amount = new Currency { currency = "USD", value = billingPlan.Amount.ToString() };
				paymentDefinition.frequency = billingPlan.Frequency.ToString();
				paymentDefinition.type = "REGULAR";
				paymentDefinition.frequency_interval = "1";

				if (billingPlan.NumberOfCycles.HasValue)
				{
					paymentDefinition.cycles = billingPlan.NumberOfCycles.Value.ToString();
				}

				plan.payment_definitions.Add(paymentDefinition);

				var created = plan.Create(apiContext);

				if (created.state == "CREATED")
				{
					var patchRequest = new PatchRequest();
					patchRequest.Add(new Patch { path = "/", op = "replace", value = new Plan() { state = "ACTIVE" } });
					created.Update(apiContext, patchRequest);
				}

				TempData["success"] = "Billing plan created.";
				return RedirectToAction("Index");
			}

			AddDropdowns();
			return View(billingPlan);
		}

		public ActionResult Details(string id)
		{
			var apiContext = Common.GetApiContext();

			var plan = Plan.Get(apiContext, id);

			return View(plan);
		}

		[HttpPost]
		public ActionResult Activate(string id)
		{
			if (!string.IsNullOrEmpty(id))
			{
				var apiContext = Common.GetApiContext();
				var plan = Plan.Get(apiContext, id);
				if (plan != null && plan.state == "CREATED")
				{
					var patchRequest = new PatchRequest();
					var tempPlan = new Plan();
					tempPlan.state = "ACTIVE";
					patchRequest.Add(new Patch { path = "/", op = "replace", value = tempPlan });
					plan.Update(apiContext, patchRequest);

					TempData["success"] = "Plan activated";
				}
			}

			return RedirectToAction("Index");
		}

		[HttpPost]
		public ActionResult Delete(string id)
		{
			if (!string.IsNullOrEmpty(id))
			{
				var apiContext = Common.GetApiContext();
				var plan = Plan.Get(apiContext, id);

				if (plan != null)
				{
					plan.Delete(apiContext);
					TempData["success"] = "Plan deleted";
				}
			}

			return RedirectToAction("Index");
		}

		private void AddDropdowns()
		{
			var types = new List<SelectListItem>
			{
				new SelectListItem { Text = "Fixed", Value = "FIXED" },
				new SelectListItem { Text = "Infinite", Value = "INFINITE" }
			};

			ViewBag.PossibleTypes = types;
		}
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Paypal Testing</title>
    @Styles.Render("~/Content/css")
	@RenderSection("head", false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Paypal Testing", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Payments", "Index", "Payments")</li>
					<li>@Html.ActionLink("Stored Cards", "Index", "Cards")</li>
					<li>@Html.ActionLink("Billing Plans", "Index", "Plans")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		<div class="page-header">
			<h1>@ViewBag.Title</h1>
		</div>

		@if (TempData.ContainsKey("success")) {
			<div class="alert alert-success alert-dismissible fade in">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				@Html.Raw(TempData["success"])
			</div>
		}

		@if (TempData.ContainsKey("error")) {
			<div class="alert alert-danger alert-dismissible fade in">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				@Html.Raw(TempData["error"])
			</div>
		}

		@if (TempData.ContainsKey("info")) {
			<div class="alert alert-info alert-dismissible fade in">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				@Html.Raw(TempData["info"])
			</div>
		}

		@RenderBody()
		<hr />
		<footer>
			<p class="text-center">&copy; @DateTime.Now.Year - Paypal Testing</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>